package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResourceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceAllPropertiesEquals(Resource expected, Resource actual) {
        assertResourceAutoGeneratedPropertiesEquals(expected, actual);
        assertResourceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceAllUpdatablePropertiesEquals(Resource expected, Resource actual) {
        assertResourceUpdatableFieldsEquals(expected, actual);
        assertResourceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceAutoGeneratedPropertiesEquals(Resource expected, Resource actual) {
        assertThat(actual)
            .as("Verify Resource auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceUpdatableFieldsEquals(Resource expected, Resource actual) {
        assertThat(actual)
            .as("Verify Resource relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getAuthor()).as("check author").isEqualTo(expected.getAuthor()))
            .satisfies(a -> assertThat(a.getKeywords()).as("check keywords").isEqualTo(expected.getKeywords()))
            .satisfies(a -> assertThat(a.getResourceType()).as("check resourceType").isEqualTo(expected.getResourceType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceUpdatableRelationshipsEquals(Resource expected, Resource actual) {
        // empty method
    }
}
